### ISSUE TITLE
Setup problem

### ISSUE THREAD

**Issue by robbarry** [openvenues/pypostal#2]
Hi there: I hit a snag when trying to follow the setup instructions. At the "python setup.py install" step, I got an error message that indicates the compiler can't find libpostal/libpostal.h.

libpostal itself seems to be correctly installed and I'm able to run it from the command line.

I'm running the OSX system version of Python 2.7.10. Before I go mucking with new Python installations or moving directories around, thought I'd post this here. Since no one else has reported this issue, it's probably something stupid on my end...

Here's what I see when I try to run setup.py. It's the same error regardless of whether I preface with `sudo`:

```
rob$ python setup.py install
running install
Checking .pth file support in /Library/Python/2.7/site-packages/
/usr/bin/python -E -c pass
TEST PASSED: /Library/Python/2.7/site-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing requirements to pypostal.egg-info/requires.txt
writing pypostal.egg-info/PKG-INFO
writing top-level names to pypostal.egg-info/top_level.txt
writing dependency_links to pypostal.egg-info/dependency_links.txt
reading manifest file 'pypostal.egg-info/SOURCES.txt'
writing manifest file 'pypostal.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.11-intel/egg
running install_lib
running build_py
running build_ext
building 'postal._expand' extension
cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c postal/pyexpand.c -o build/temp.macosx-10.11-intel-2.7/postal/pyexpand.o -std=c99 -Wno-unused-function
postal/pyexpand.c:2:10: fatal error: 'libpostal/libpostal.h' file not found
#include <libpostal/libpostal.h>
         ^
1 error generated.
error: command 'cc' failed with exit status 1
```

**Comment by thatdatabaseguy** [comment]
Hey Rob. Are you running Yosemite/El Cap?

If you have pkg-config installed (if not ```brew install pkg-config``` and reinstall libpostal), can you post the output of ```pkg-config --cflags libpostal```?

**Comment by robbarry** [comment]
I'm running El Capitan. Here's what I see:
```
rob$ pkg-config --cflags libpostal
-I/usr/local/include
```

**Comment by thatdatabaseguy** [comment]
Ok, just added some default compile args. Had to do something similar for ElCap in the Node build. Can you try again with the latest changes?

**Comment by robbarry** [comment]
Okay, that seems to have gotten things a bit further. Now here's my error:

```
rob$ python setup.py install
running install
Checking .pth file support in /Library/Python/2.7/site-packages/
/usr/bin/python -E -c pass
TEST PASSED: /Library/Python/2.7/site-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing requirements to pypostal.egg-info/requires.txt
writing pypostal.egg-info/PKG-INFO
writing top-level names to pypostal.egg-info/top_level.txt
writing dependency_links to pypostal.egg-info/dependency_links.txt
reading manifest file 'pypostal.egg-info/SOURCES.txt'
writing manifest file 'pypostal.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.11-intel/egg
running install_lib
running build_py
running build_ext
building 'postal._expand' extension
cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c postal/pyexpand.c -o build/temp.macosx-10.11-intel-2.7/postal/pyexpand.o -std=c99 -I/usr/local/include -L/usr/local/lib -Wno-unused-function
clang: warning: argument unused during compilation: '-L/usr/local/lib'
postal/pyexpand.c:239:1: warning: unused label 'exit_decref_unistr' [-Wunused-label]
exit_decref_unistr:
^~~~~~~~~~~~~~~~~~~
1 warning generated.
postal/pyexpand.c:239:1: warning: unused label 'exit_decref_unistr' [-Wunused-label]
exit_decref_unistr:
^~~~~~~~~~~~~~~~~~~
1 warning generated.
cc -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. build/temp.macosx-10.11-intel-2.7/postal/pyexpand.o -lpostal -o build/lib.macosx-10.11-intel-2.7/postal/_expand.so
ld: library not found for -lpostal
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'cc' failed with exit status 1
```

**Comment by thatdatabaseguy** [comment]
Ah, incorrect setup.py args on my part. Try the change I just pushed.

**Comment by robbarry** [comment]
Okay, I think that worked! Unfortunately, the module doesn't seem to import correctly.

```
Python 2.7.10 (default, Oct 23 2015, 18:05:06) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from postal.expand import expand_address
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "postal/expand.py", line 5, in <module>
    from postal import _expand
ImportError: cannot import name _expand
```

However, I'm able to run `import postal` without a problem:

```
>>> import postal
>>> dir(postal)
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__']
```

**Comment by robbarry** [comment]
If I'm running Python in the directory with pypostal's source code, the above works fine, just FYI.

**Comment by thatdatabaseguy** [comment]
Yeah, there's a note about that case in the README. To run from your source checkout, just run ```python setup.py build_ext --inplace``` so the extension modules will be there locally on import.

**Comment by robbarry** [comment]
Oops. Works. Thanks!

**Comment by thatdatabaseguy** [comment]
No problem, thanks for checking it out!
