### ISSUE TITLE
Error "Cannot allocate memory" when importing `parse_address`

### ISSUE THREAD

**Issue by munikarmanish** [openvenues/pypostal#40]
I just followed the installation instructions in the README in a fresh Ubuntu 18.10 machine. `expand_address` works well, but it throws error when importing `parse_address`.

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from postal.expand import expand_address
>>> from postal.parser import parse_address
ERR   Error loading address parser module, dir=(null)
   at libpostal_setup_parser_datadir (libpostal.c:410) errno: Cannot allocate memory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.local/share/virtualenvs/test-_wVQhZDO/lib/python3.6/site-packages/postal/parser.py", line 2, in <module>
    from postal import _parser
SystemError: initialization of _parser raised unreported exception
>>>
```

Also, I checked RAM usage and there is still about 1.5 GB memory available. So I'm not sure why it _cannot allocate memory_.

Did I miss something?

**Comment by w0pr** [comment]
You need still more memory for initializing libpostal; 4GB should be ok, but you could try ltrace to figure out the exact amount requested by libpostal:

`ltrace -F ltrace.conf -s 9999 -l 'libpostal*' -o ltrace.txt python -c pypostal_test.py`
