### ISSUE TITLE
Fails to install from pip with a complaint about a missing README

### ISSUE THREAD

**Issue by shaleh** [openvenues/pypostal#52]
```
pip install pypostal
Collecting pypostal
  Downloading https://files.pythonhosted.org/packages/e7/96/145d60501264de505926f48f52c29c5fd20d066f2e158107a66ea963cf56/pyPostal-1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-x4mnpikd/pypostal/setup.py", line 10, in <module>
        long_description=codecs.open('README.rst', "r", "utf-8").read(),
      File "/var/lang/lib/python3.7/codecs.py", line 898, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-x4mnpikd/pypostal/
```

**Comment by shaleh** [comment]
Nevermind, I see the complaint about name collisions.
