### ISSUE TITLE
ImportError: DLL load failed while importing _parser: The specified module could not be found

### ISSUE THREAD

**Issue by lukeoz** [openvenues/pypostal#73]
After chipping away and finally being able to install the postal package on my Windows installation of Python, many thanks to [this thread](https://github.com/openvenues/pypostal/issues/23), I have come unstuck when trying to run an example script, specifically this:

```
from postal.parser import parse_address
parse_address('The Book Club 100-106 Leonard St Shoreditch London EC2A 4RH, United Kingdom')
```

It returns an error saying: 
```
PS C:\Users\lukeoz> & python c:/Users/Me/AppData/Roaming/Python/Python39/site-packages/postal/tmp.py
Traceback (most recent call last):
  File "c:\Users\lukeoz\AppData\Roaming\Python\Python39\site-packages\postal\tmp.py", line 1, in <module>
    from postal.parser import parse_address
  File "C:\Users\lukeoz\AppData\Roaming\Python\Python39\site-packages\postal\parser.py", line 2, in <module>
    from postal import _parser
ImportError: DLL load failed while importing _parser: The specified module could not be found.
```

Is it trying to load the libpostal.dll file that was saved in C:\libpostal when I installed the C package? I have added C:\libpostal to my Path in my environment variables, but with no change to the outcome.

The same error happens while trying to import _expand as well.

Has anyone had this error before or recognises what the problem might be?

Many thanks in advance

**Comment by rhartopBBK** [comment]
Am also having this issue

**Comment by wildflower** [comment]
many thanks to you :) 
I had to copy it into 
$localhome\AppData\Roaming\Python\Python313\site-packages\postal
